version: '3'
services:
  server:
    build: .
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n"
    image: star-wars-universe
    ports:
      - "8080:8080"
      - "5005:5005"
