package com.example.entrypoint;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class GetUsersTest {
    @Test public void testSomeLibraryMethod() {
        GetUsers classUnderTest = new GetUsers();
        //assertEquals("someLibraryMethod should return 'true'", classUnderTest.get().getN, "Hello");
    }
}
