package com.example.entrypoint;

import java.util.Arrays;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.example.core.model.User;
import com.example.core.usecases.GetUserInfoUseCase;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Component
@RestController
public class GetUsers {
	@Autowired
	private GetUserInfoUseCase getUserInfoUseCase;

	@RequestMapping(produces = "application/json", method = RequestMethod.GET, path = "/users/{id}")
	public User get(@PathVariable int id) {
		return getUserInfoUseCase.get(id);
	}

	@GetMapping("/users")
	public List<User> get() {
		return Arrays.asList(getUserInfoUseCase.get());
	}
}
